services:
  - type: web
    name: telegram-sender
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 8 -k gthread --timeout 300 app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: FLASK_SECRET
        generateValue: true
      - key: DATA_DIR
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
